### PR TITLE
FIX #1649 Reflets.info updated

### PR DESCRIPTION
**Pull request by Simounet**
Hi there,
I updated the reflets.info configuration to make it working again.

### CODE REVIEW

**Comment by Simounet** [comment]
Might FIX https://github.com/wallabag/wallabag/issues/1649 .

**Comment by j0k3r** [comment]
Thanks for that @Simounet !

Could you better submit a PR to https://github.com/fivefilters/ftr-site-config instead? I regularly update this repo from the upstream one and it's better to keep one place for site-config :)

**Comment by Simounet** [comment]
Of course. I'll do that right now.

**Comment by Simounet** [comment]
Done: https://github.com/fivefilters/ftr-site-config/pull/194

**Pull request closed without merging**
