### PR TITLE
Create Paywall alternatives-economiques.fr.txt

### PR DESCRIPTION
**Pull request by biva**
Please push your site_config changes at fivefilters/ftr-site-config instead.
I regularly merge the upstream in that repo (so you don't need to duplicate your effort).

### CODE REVIEW

**Comment by j0k3r** [comment]
Did you read the GitHub template?
It says that you should push your changes at https://github.com/fivefilters/ftr-site-config instead of here.

**Comment by biva** [comment]
OK, but on Gitter @tcitworld told me that for paywall, I shouldn't push it on figefilters, because they are not interested in it. What should I do?

**Comment by j0k3r** [comment]
Wow sorry I was too quick to check that.
Because the template wasn't updated and no real description was provided in the PR I decided to quickly.

Next time, don't forget to update the description of your PR so we won't lose time in extra conversation :slightly_smiling_face:

**Comment by biva** [comment]
ok :)

**Comment by biva** [comment]
The last version does work for some articles, but not all of them. And without credentials. I'm not able to find the right way for the paywall :(

In addition, I'm not able to parse graphs inside the article. There's a block ```div.c-bloc-medias__inner``` but I don't know how to integrate it.

Thank you for your help

**Comment by biva** [comment]
And for the paywall, without credentials, this article is parsed: https://www.alternatives-economiques.fr/solidarite-a-minima-face-a-crise-migratoire/00080307
But not this one: https://www.alternatives-economiques.fr/un-signal-dalarme-toute-gauche-europeenne/00080515

Last question: I don't know how to verify if my config is OK for author and date. Could you help me?

(my wallabag: 2.2.3)

**Comment by j0k3r** [comment]
To fully debug, you can use https://f43.me/feed/test
Put your config file and the url of an article.
Once parsed, jump to the _debug log_ tab.
Scroll to the bottom and you'll data return by graby

**Comment by biva** [comment]
Thank you. It looks fine, author and date are returned correctly. There's only a small mistake at the beginning, the first word of the article is parsed in the body. I can't undersatnd why.

Impossible to investigate further: I get a "cURL Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received" :(

**Comment by biva** [comment]
> Please push your site_config changes at fivefilters/ftr-site-config instead. I regularly merge the upstream in that repo (so you don't need to duplicate your effort).

OK, done here: https://github.com/fivefilters/ftr-site-config/pull/377

I close this one.

**Pull request closed without merging**
