### PR TITLE
Added LesJours.fr

### PR DESCRIPTION
**Pull request by nicosomb**
I can't fetch the author of the article. Please help me :-)

### CODE REVIEW

**Comment by tcitworld** [comment]
Author is inside `<span itemprop="name">`.
Published date can be set to `<meta property="article:published_time" content="2017-11-21T23:05:00.000Z"/>`

**Comment by nicosomb** [comment]
I saw where the author is but I can't get it via xpath. 
The publication date is already ok.

**Comment by aaa2000** [comment]
You can try with `(//article//span[@itemprop="author"]/span[@itemprop="name"])[1]`, in firefox console, you get it by ` $x('(//article//span[@itemprop="author"]/span[@itemprop="name"])[1]')`

**Comment by nicosomb** [comment]
It doesn't work with your proposal, @aaa2000.

**Comment by aaa2000** [comment]
and with `//article//span[@itemprop="author" and contains(@class, "link")]/span[@itemprop="name"]`

**Comment by aaa2000** [comment]
With a config, it works locally on master but not in https://f43.me/feed/test

```
author: //article//span[@itemprop="author" and contains(@class, "link")]/span[@itemprop="name"]
tidy:no
```

**Comment by nicosomb** [comment]
Not here on master branch and with this file:
```
title://h1[@class="h2"]
author: //article//span[@itemprop="author" and contains(@class, "link")]/span[@itemprop="name"]
body: //div[@class="article-holder"]

tidy:no

# Wallabag-specific login directives (not supported in FTR)
requires_login: yes

login_uri: https://lesjours.fr/session
login_username_field: mail
login_password_field: password

not_logged_in_xpath: //body[@class="not-logged-in"]

test_url: https://lesjours.fr/obsessions/pole-financier/ep12-marcel-campion/
```

**Comment by j0k3r** [comment]
Without tidy, I got:

```html
<div class="col sm-w-6c md-w-8c lg-w-8c">
<address class="style-meta">

Texte

Camille Polloni 


Photo

Henri Collot/Sipa 

</address>
</div>
```

🤔

**Comment by aaa2000** [comment]
I had to make a mistake then. I need to check this evening if I not commented `'clean' => true` in `php-readability/src/Readability.php`

**Comment by nicosomb** [comment]
@j0k3r we can maybe merge this PR, and we'll improve the author part in an other one.

**Pull request merged**
