### PR TITLE
twitter: add support of single_page_link to follow articles

### PR DESCRIPTION
**Pull request by Kdecherf**

### CODE REVIEW

**Comment by tcitworld** [comment]
So saving a tweet will also save the article linked inside ? Not sure if this should be a default behaviour

**Comment by j0k3r** [comment]
In fact, saving a tweet will save the linked article if it exist. Otherwise, it'll still save the tweet.
Don't know if this should be the default behavior too.

**Comment by Kdecherf** [comment]
Is there any way to make a section of siteconfig optional (via addons or boolean setting)?

**Comment by j0k3r** [comment]
Nope 😕

**Comment by gnppn** [comment]
Hi!

As discussed on Twitter, I'd really like saving the article instead of the tweet to be the default behaviour. This is what I use it for on Twitter, and I'd use the Twitter bookmarks a lot less.

I remember some years ago that Pocket used to save the article, and present the parent tweet as context (via a bar at the bottom of the app on mobile).

Thank you :)

**Pull request closed without merging**
