### PR TITLE
Added mediapart.fr config

### PR DESCRIPTION
**Pull request by bdunogier**
Mostly login configuration. Parsing looks okay.

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you add a `test_url` at the end?

**Comment by bdunogier** [comment]
Done.

**Comment by j0k3r** [comment]
I've no idea why I didn't merge that.

**Comment by fradav** [comment]
Some recent changes in the site (div -> section) made this config broken.
@bdunogier, could you have a look to update the config ? 
Thanks for the good work anyway

**Pull request merged**
